"""Initial migration

Revision ID: ca4d1efb09ef
Revises:
Create Date: 2026-03-03 23:14:26.998624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm
from openid_server.security import generate_key_pair, KeyAlgorithm

# revision identifiers, used by Alembic.
revision: str = "ca4d1efb09ef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    keyalgorithm_enum = sa.Enum("RS256", "EdDSA", name="keyalgorithm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_store",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("alg", keyalgorithm_enum, nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("secret_key", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_update_key", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("family_name", sa.String(), nullable=True),
        sa.Column("given_name", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "client",
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret", sa.String(), nullable=False),
        sa.Column("redirect_uris", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column(
            "preferred_algorithm",
            keyalgorithm_enum,
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "authorization_code",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("response_mode", sa.String(), nullable=False),
        sa.Column("code_challenge", sa.String(), nullable=True),
        sa.Column("code_challenge_method", sa.String(), nullable=True),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("auth_time", sa.DateTime(), nullable=False),
        sa.Column("nonce", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.client_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    # ### end Alembic commands ###

    # Create two initial keys for the key store.
    ks1 = generate_key_pair(KeyAlgorithm.EdDSA).to_keystore()
    ks2 = generate_key_pair(KeyAlgorithm.RS256).to_keystore()
    session = orm.Session(bind=op.get_bind())
    session.add(ks1)
    session.add(ks2)
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authorization_code")
    op.drop_table("client")
    op.drop_table("user")
    op.drop_table("key_store")
    # ### end Alembic commands ###
